package models;

import com.avaje.ebean.validation.NotNull;
import javax.persistence.*;
import play.db.ebean.*;

/**
 * Book reference.
 */
@Entity
public class Reference extends Model {

    /**
     * A unique, automatically generated key.
     */
    @Id
    private Integer id;

    /**
     * Cite key used for uniquely identifying the reference within a
     * LaTex document. Required field.
     */
    @NotNull
    public String citeKey;

    /**
     * Publisher address. Optional field.
     */
    public String address;

    /**
     * Author name(s). Required field.
     */
    @NotNull
    public String author;

    /**
     * Edition of a book. Optional field.
     */
    public String edition;

    /**
     * Publisher. Required field.
     */
    @NotNull
    public String publisher;

    /**
     * Title. Required field.
     */
    @NotNull
    public String title;

    /**
     * Volume of a book. Optional field.
     */
    public Integer volume;

    /**
     * Publishing year. Required field.
     */
    @NotNull
    public Integer year;

    /**
     * Constructs a reference type with all the compulsory fields.
     * @param citeKey
     * @param title
     * @param author
     * @param publisher
     * @param year
     */
    public Reference(String citeKey, String title, String author, String publisher,
            int year) {
        this.citeKey = citeKey;
        this.title = title;
        this.author = author;
        this.publisher = publisher;
        this.year = year;
    }

    /**
     * Returns the autogenerated id or null if the reference has not
     * been saved to database.
     * @return
     */
    public int getId() {
        return id;
    }
}
